### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [hirvoin/ecommerce-frontend#1]
# Katselmointi

Terve @hirvoin! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröin uuden käyttäjän
- Kirjauduin sisään uudella käyttäjälläni
- Katsoin käyttäjätietoni
- Selasin etusivun tuotteita
- Selasin ja filtteröin tuotesivun tuotteita
- Lisäsin pari tuotetta ostoskoriin
- Avasin ostoskorin ja muokkasin tuotteiden määriä
- Lähetin tilauksen
- Tyhjensin ostoskorin
- Kirjauduin ulos

### Kokemus

- Käyttöliittymä on suurimmilta osin selkeä ja helppokäyttöinen, hyvää työtä! 🏆
- Rekisteröitymis- ja kirjautumislomakkeissa voisi näyttää jonkinlaisen virheilmoituksen, kun kentät on syötetty väärin
- Rekisteröitymislomakkeessa voisi tulla jokin ilmoitus kun rekisteröityminen on onnistunut. Kätevintä olisi, jos käyttäjä vain automaattisesti kirjautuisi sisään
- Ostoskorissa kokonaishinta voisi päivittyä suoraan, kun muuttaa tuotetteiden määriä
- Tilauksen lähettämisen jälkeen ostoskori voisi tyhjentyä ja käyttäjän voisi siirtää esim. etusivulle. Näin vältyttäisiin vahinkotilauksilta
- Geneerisen "React App"-faviconin voisi muuttaa kuvaavammaksi

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Styled-componentsin kanssa kannattaa käyttää [konfiguroitavaa teemaa](https://styled-components.com/docs/advanced#theming). Tämä helpottaa pitämään käyttöliittymän ulkoasun yhtenäisenä ja ylläpidettävänä
- Formikin käyttö lomakkeiden tilanhallinnassa on hyvä idea. Kannattaa toteuttaa uudelleenkäytettäviä lomakekomponentteja, joihin on toteutettu mm. tilanhallinta ja virheviestien näyttäminen. Esim. tähän tapaan:

```javascript
const FormikInput = ({ name, ...props }) => {
  const [field, meta, helpers] = useField(name);
  const showError = meta.touched && meta.error;

  return (
    <>
      <StyledInput
        onChange={(e) => helpers.setValue(e.target.value)}
        onBlur={() => helpers.setTouched(true)}
        value={field.value}
        error={showError}
        {...props}
      />
      {showError && <div>{meta.error}</div>}
    </>
  );
};

// ...

<FormikInput
  name="username"
  label="Username"
  id="username"
  placeholder="Enter your username"
  type="text"
/>;
```

- [Datan haku](https://github.com/hirvoin/ecommerce-frontend/blob/master/src/App.js#L38) kannattaa yleensä tehdä "laiskasti", eli haetaan data vasta kun sitä käyttävä komponentti mountatataan. Datan haun voi tehdä myös täysin ilman Reduxia, esim. hookien avulla. Yksi hyvä kirjasto tähän tarkoitukseen on [swr](https://swr.now.sh/)
- Syvien tietorakenteiden immutable päivittäminen Reduxin reducereissa puhtaalla JavaScriptilla on melko työlästä. [Immer](https://www.npmjs.com/package/immer)-kirjasto helpottaa tätä huomattavasti
- [Redux Toolkit](https://redux-toolkit.js.org/) tarjoaa todella hyviä työkaluja Reduxin käyttöön. Esim. [createReducer](https://redux-toolkit.js.org/usage/usage-with-typescript#createreducer)-funktio vähentää reducerien boilerplate koodia huomattavasti. Se käyttää sisäisesti Immer-kirjastoa, joten myös tilan päivittäminen helpottuu
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- Reittien käsittelijöiden ainaisista `try { ... } catch (e) { next(e) }`-lohkoista pääsee helposti eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjaston avulla
- `toJSON`-metodikutsut eivät ole tarpeen [reitin käsittelijöissä](https://github.com/hirvoin/ecommerce-backend/blob/master/src/controllers/orders.js#L16), koska niitä kutsutaan automaattisesti kun lähetettävä data serialisoidaan JSON-muotoon. Tämä tulee ilmi [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)-dokumentaatiosta
- Autentikaatiotokenin ekstraktoinnin kyselystä ja sen verifioinnin voisi siirtää omaan middlewareensa

## Kokonaisuus

- Käyttökelpoinen verkkokauppasovellus, jossa on selkeä ja pääosin käyttäjäystävällinen käyttöliittymä. Rekisteröitymisen ja tilauksen lähettämisen jälkeistä käyttökokemusta voisi parantaa, ettei käyttäjä jäisi epätietoisuuden tilaan, tai tekisi vahingossa samaa tilausta kahteen kertaan
- Koodi on hyvin organisoitua ja sen sisäinen laatu on pääsääntöisesti hyvällä mallilla

**Comment by hirvoin** [comment]
Kiitos @Kaltsoon hyvästä, rakentavasta palautteesta!
